name = "Toralia"
author = "Alfakynz"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "623b038b419e459620ab31aaba5c07ddd3062960118b351933e00a6fef1f8b8c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
